query GetAnimeDetails($id: Int!) {
  Media(id: $id, type: ANIME) {
    id

    title {
      romaji
      english
      native
    }

    startDate { year }
    endDate { year }

    description(asHtml: true)
    format
    status
    season
    seasonYear
    episodes
    duration
    averageScore
    popularity
    favourites
    bannerImage
    genres

    coverImage {
      extraLarge
      large
      medium
    }

    studios(isMain: true) {
      nodes {
        name
      }
    }
  
    trailer {
      id
      site
      thumbnail
    }

    streamingEpisodes {
      title
      thumbnail
      site
      url
    }

    staff(sort: [RELEVANCE, FAVOURITES_DESC]) {
      edges {
        role
        node {
          id
          name {
            full
            native
          }
          image {
            large
          }
        }
      }
    }

    relations {
      edges {
        relationType
        node {
          id
          type
          format
          startDate { year }
          endDate { year }
          title {
            romaji
            english
          }
          coverImage {
            large
          }
        }
      }
    }

    characters(perPage: 6, sort: [RELEVANCE, FAVOURITES_DESC]) {
      edges {
        role
        node {
          id
          name {
            full
            native
          }
          image {
            large
          }
        }
      }
    }
  }
}
