query GetCharacterById($id: Int!, $page: Int, $perPage: Int) {
Character(id: $id) {
    id
    name {
      full
      native
      alternative
    }
    image { large }
    description
    favourites
    age
    gender
    bloodType
    
    dateOfBirth { year month day }

    media(page: $page, perPage: $perPage) {
      nodes {
        id
        format
        seasonYear
        averageScore
        title { romaji english }
        coverImage { large medium }
      }
      edges {
        node {
          id
        }
        voiceActors {
          age
          bloodType
          id
          name {
            full
          }
        }
      }
      pageInfo { total hasNextPage currentPage }
    }
  }
}
