query GetStaffById($id: Int!, $page: Int, $perPage: Int) {
  Staff(id: $id) {
    id
    name {
      full
      native
      alternative
    }
    image {
      large
    }
    description(asHtml: true)
    primaryOccupations
    gender
    dateOfBirth {
      year
      month
      day
    }
    dateOfDeath {
      year
      month
      day
    }
    age
    yearsActive
    homeTown
    bloodType
    favourites

    staffMedia(page: $page, perPage: $perPage) {
      nodes {
        id
        title {
          romaji
          english
        }
        coverImage {
          large
          medium
        }
        format
        seasonYear
        averageScore
      }
      pageInfo {
        total
        hasNextPage
      }
    }
  }
}
