query TODAY_BIRTHDAYS_QUERY($perPage: Int, $sort: [CharacterSort]) {
  Page(page: 1, perPage: $perPage) {
    characters(
      isBirthday: true,
      sort: $sort
    ) {
      id
      name {
        full
        native
      }
      image {
        large
      }
      favourites
      media(perPage: 1) {
        nodes {
          title {
            romaji
            english
          }
        }
      }
    }
  }
}