query TODAY_BIRTHDAYS_QUERY($page: Int, $perPage: Int, $sort: [CharacterSort]) {
  Page(page: $page, perPage: $perPage) {
    characters(sort: $sort) {
      id
      name {
        full
        native
      }
      dateOfBirth {
        month
        day
      }
      image {
        large
      }
      favourites
      media(perPage: 1) {
        nodes {
          title {
            romaji
            english
          }
        }
      }
    }
  }
}
