query GetCharacterById($id: Int!) {
  Character(id: $id) {
      id
      name {
        full
        native
        alternative
      }
      image {
        large
      }
      description
      favourites

      age
      gender
      bloodType

      dateOfBirth {
        year
        month
        day
      }

      media(perPage: 12) {
        nodes {
          id
          format
          seasonYear
          averageScore
          title {
            romaji
            english
          }
          coverImage {
            large
            medium
          }
        } 
      }
  }
}